### PR TITLE
Fix #38 - closing inputStreams

### LINKED ISSUE #38: CompileTask should better close the source files input stream
The `CompileTask` should call the `close() ` method on the inputStreams of the jrxml files it compiles.

It's a minor issue, but it's still one.

### PR DESCRIPTION
**Pull request by brunoabdon**
The `FileInputStream`s are now properly closed.

### CODE REVIEW

**Comment by alexnederlof** [comment]
Thanks! Can you fix the indentation?

**Comment by brunoabdon** [comment]
Yes, I can. I tried to change the code as few as possible. Since the indentation was a little bit irregular in the original code, I kept it as it was.

**Comment by alexnederlof** [comment]
I don't mind either approach

**Comment by brunoabdon** [comment]
Done.

**Comment by alexnederlof** [comment]
Great!

**Comment by alexnederlof** [comment]
This PR broke a test on master @brunoabdon, which blocks the release. Do you have time to look into it? Otherwise I have to revert.

```
testNonExistentFolderAllowed(com.alexnederlof.jasperreport.JasperReportTest)  Time elapsed: 0.061 sec  <<< ERROR!
java.lang.IllegalArgumentException: nonExistentFolder is not a directory
	at com.alexnederlof.jasperreport.JasperReporter.jrxmlFilesToCompile(JasperReporter.java:218)
	at com.alexnederlof.jasperreport.JasperReporter.execute(JasperReporter.java:182)
	at com.alexnederlof.jasperreport.JasperReportTest.getAndExecuteMojo(JasperReportTest.java:147)
	at com.alexnederlof.jasperreport.JasperReportTest.testNonExistentFolderAllowed(JasperReportTest.java:259)
```

**Comment by brunoabdon** [comment]
I'll take a look

**Comment by brunoabdon** [comment]
The `testNonExistentFolderAllowed` test, introduced in january 21 seems mistaken.

The Javadoc says 

"_Test that a non-existent sourceDirectory just be skipped if failOnMissingSourceDirectory=true._"

but actually,  a non-existing sourceDirectory should cause a failure (instead of being skipped) when the property `failOnMissingSourceDirectory` is set to `true`.

**Comment by brunoabdon** [comment]
Indeed there was a mistake. Fixed on #40.

**Pull request merged**
